### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by RapidAPI-Packages**
Hey there. I added a link in your README to a tool I built where you can test out the API calls in your browser before using your SDK to connect to the API. I've built something similar for other SDKs (Telegram, Shopify and LinkedIn) and gotten feedback that it was pretty useful. If anything, let me know what you think and if you have any feedback.

### CODE REVIEW

**Comment by jaraco** [comment]
Looks reasonable. Can you put the badge adjacent to the other badges?

**Comment by RapidAPI-Packages** [comment]
Done!

**Comment by aemino** [comment]
I'd like to respectfully advise against this. This user has been making PRs on lots of different repositories asking to add his badge.

**Comment by jaraco** [comment]
@aemino I was a little uneasy with the badge as well. It does feel a little bit like he's asking this project to promote his service, which is fine if the service it's promoting in fact benefits this project and improves the experience for the users. If on the other hand, it's only a cheap way to promote a commercial product or to drive traffic to a site for revenue, then I agree, I don't want it. I was going to accept the PR but was also willing to revert the changes if I found later that users found it objectionable. Can you articulate what your objection is? If the objection is just that he's made PRs to other projects that might see similar benefit, that's not enough to convince me to reject it.

At the same time, given the objection, I'd like @RapidAPI-Packages to elaborate a bit on (or link to) what are the benefits of the service and how it would benefit users of this package.

**Comment by jaraco** [comment]
I also note that the service doesn't actually use this library, but uses its own implementation of the API (in PHP), so it has a tenuous connection to this library. In that sense, it provides little benefit over the [primary user interface](http://www.wolframalpha.com/) while having the additional downside of requiring the user to submit their API key to a third party.

In consideration of that, I now feel that directing users to this site is potentially dangerous.

**Comment by aemino** [comment]
I'm not going to tell you what to do; it is your choice. My only objection is that the way the user has been asking repository managers to add his badge is not genuine. It simply feels like the user is only making a feeble attempt to promote his questionably useful service.

**Comment by jaraco** [comment]
As I haven't heard anything more from the original requester, I'm closing this request. Feel free to answer my questions above and I may reconsider.

**Pull request closed without merging**
